development:
      host: localhost
      adapter: mysql
      database: fedena_br
      port: 8889
      username: root
      password: root

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 8889
      username: admin
      password:

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 8889
      username: admin
      password: 
cucumber:
  <<: *test